services:
  - type: web
    name: backend
    env: node
    region: singapore   # you can switch to another close region if Render supports it
    plan: free
    branch: main
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: RAZORPAY_KEY
        sync: false
